name: Build and Package JAR

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
      
    - name: Create javadoc
      run: mvn javadoc:javadoc
      
    - name: Build with Maven
      run: mvn package

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-app-jar
        path: target/*.jar
